<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>eSports_arena_manager</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <packaging>pom</packaging>
    <modules>
        <module>users-service</module>          <!--00-->
        <module>auth-service</module>           <!--01-->
        <module>game-service</module>           <!--02-->
        <module>team-service</module>           <!--03-->
        <module>tournament-service</module>     <!--04-->
        <module>registration-service</module>   <!--05-->
        <module>match-service</module>          <!--06-->
<!--        <module>result-service</module>-->  <!--07-->
        <module>ranking-service</module>        <!--08-->
        <module>sanction-service</module>       <!--09-->
<!--        <module>prize-service</module>-->   <!--10-->
       <module>notification-service</module>    <!--11-->
    </modules>

</project>