spring.application.name=prize-service
server.port=8011

# Configuración de Base de Datos H2 en Memoria
spring.datasource.url=jdbc:h2:mem:prizedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs de las consultas SQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update